### PR TITLE
Add InertiaJS v2 Support

### PR DESCRIPTION
**Pull request by mysticseagull**
Add support for InertiaJS v2

### CODE REVIEW

**Comment by gainlinejono** [comment]
@lepikhinb are you able to approve this PR please?

**Comment by ralphjsmit** [comment]
@lepikhinb Can you please merge this PR? Thank you!

**Comment by onlime** [comment]
until then, I have added this howto: https://github.com/lepikhinb/momentum-modal-plugin/pull/16#issuecomment-2551731542

**Comment by mysticseagull** [comment]
If nothing is done, I might actually just start working on my fork and adding features/bugfixes to it. 

I will keep this thread up-to-date with my decision sooner rather than later, but I will wait another couple weeks to see if any changes occur.

**Comment by lepikhinb** [comment]
Sorry guys. Getting back 👌🏻 Thanks for the heads up

**Pull request merged**
